### ISSUE TITLE
waiterbot: erroneous early approach success

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki-x#14]
Sometimes when approaching the VM, the pose controller reports a success way to early. Find out what is causing this and fix it.

**Comment by jihoonl** [comment]
Can you give me rough number that how many times it fail out of 10?

**Comment by bit-pirate** [comment]
I also removed result publishing by the pose controller when tracking a new goal: https://github.com/yujinrobot/yujin_ocs/commit/320ad5ba70db8ec5991ec38f68253c529291f94a

**Comment by bit-pirate** [comment]
Tested and works.
