### ISSUE TITLE
marker approach: handle controller failure

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki-x#17]
Add logic to the approach node to handle the situation when the pose controller fails to reach the goal: https://github.com/yujinrobot/kobuki-x/blob/ar_approaching/waiterbot_suite/waiterbot_ar_pair_approach/src/waiterbot_ar_pair_approach/node.py#L121

**Comment by jihoonl** [comment]
The issue has been migrated to yujin_ocs. ar pair approach has moved to new repository.
