### ISSUE TITLE
improve the behavior of safety controller.

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki-x#6]

**Comment by bit-pirate** [comment]
Please describe what needs to be improved.

**Comment by jihoonl** [comment]
When safety controller is enabled, it continuously goes back and forth. It should behave in smarter way.

**Comment by bit-pirate** [comment]
This issue has already been raised here: https://github.com/yujinrobot/kobuki/issues/261
Follow the existing issue for updates.
